<!-- Slider -->
<section id="slide">
    <div id="carousel" class="carousel slide" data-ride="carousel">
        <ul class="carousel-indicators">
            <li data-target="#carousel" data-slide-to="0" class="active"></li>
            <li data-target="#carousel" data-slide-to="1"></li>
            <li data-target="#carousel" data-slide-to="2"></li>
        </ul>
        <div class="carousel-inner">
            <div class="carousel-item carousel-image-1 active">
                <div class="container">
                    <div class="carousel-caption d-none d-sm-block text-right mb-5">
                        <h1 class="display-3 title-color">221b Baker Street Interior</h1>
                        <p class="lead">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Cum neque laborum
                            dicta hic odio tempora quod labore consequuntur dolore sint culpa distinctio saepe
                            perferendis deserunt, delectus tenetur consequatur maxime ducimus.</p>
                        <a href="#" class="btn btn-color slide-btn btn-lg">See more</a>
                    </div>
                </div>
            </div>
            <div class="carousel-item carousel-image-2">
                <div class="container">
                    <div class="carousel-caption d-none d-sm-block text-right mb-5">
                        <h1 class="display-3 title-color">Title two</h1>
                        <p class="lead">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Cum neque laborum
                            dicta hic odio tempora quod labore consequuntur dolore sint culpa distinctio saepe
                            perferendis deserunt, delectus tenetur consequatur maxime ducimus.</p>
                        <a href="#" class="btn btn-color slide-btn btn-lg">Learn more</a>
                    </div>
                </div>
            </div>
            <div class="carousel-item carousel-image-3">
                <div class="container">
                    <div class="carousel-caption d-none d-sm-block text-right mb-5">
                        <h1 class="display-3 title-color">Title three</h1>
                        <p class="lead">Lorem ipsum dolor sit amet consectetur, adipisicing elit. Cum neque laborum
                            dicta hic odio tempora quod labore consequuntur dolore sint culpa distinctio saepe
                            perferendis deserunt, delectus tenetur consequatur maxime ducimus.</p>
                        <a href="#" class="btn btn-color slide-btn btn-lg">More</a>
                    </div>
                </div>
            </div>
            <a href="#carousel" data-slide="prev" class="carousel-control-prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a href="#carousel" data-slide="next" class="carousel-control-next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>
    </div>
</section>
<!-- End of Slider -->

<!-- Service -->
<section class="services py-5 text-center">
    <div class="container">
        <div class="row">
            <!-- Single Service -->
            <div class="co1-10 mx-auto col-md-6 col-lg-4 my-3">
                <span class="service-icon">
                    <i class="fas fa-globe fa-2x"></i>
                </span>
                <h5 class="font-weight-bold text-uppercase">
                    Worldwide Shipping
                </h5>
                <p class="text-capitalize">
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium exercitationem asperiores
                    expedita iste iure reiciendis illum temporibus dolorem. Minus impedit iure odit accusantium ex
                    reprehenderit veniam? Iste quo consequatur earum?
                </p>
            </div>
            <!-- End of Single Service -->
            <!-- Single Service -->
            <div class="co1-10 mx-auto col-md-6 col-lg-4 my-3">
                <span class="service-icon">
                    <i class="fas fa-stamp fa-2x"></i>
                </span>
                <h5 class="font-weight-bold text-uppercase">
                    Certified by Gurus
                </h5>
                <p class="text-capitalize">
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium exercitationem asperiores
                    expedita iste iure reiciendis illum temporibus dolorem. Minus impedit iure odit accusantium ex
                    reprehenderit veniam? Iste quo consequatur earum?
                </p>
            </div>
            <!-- End of Single Service -->
            <!-- Single Service -->
            <div class="co1-10 mx-auto col-md-6 col-lg-4 my-3">
                <span class="service-icon">
                    <i class="fas fa-file-invoice-dollar fa-2x"></i></i>
                </span>
                <h5 class="font-weight-bold text-uppercase">
                    30 Days Money Back
                </h5>
                <p class="text-capitalize">
                    Lorem ipsum dolor sit, amet consectetur adipisicing elit. Accusantium exercitationem asperiores
                    expedita iste iure reiciendis illum temporibus dolorem. Minus impedit iure odit accusantium ex
                    reprehenderit veniam? Iste quo consequatur earum?
                </p>
            </div>
            <!-- End of Single Service -->
        </div>
    </div>
</section>
<!-- End of Service -->

<!-- Featured products -->
<section id="products" class="products py-5">
    <div class="container">
        <!-- Section title -->
        <div class="row">
            <div class="col-10 mx-auto col-sm-6 text-center">
                <h1 class="text-capitalize product-title">
                    Featured Products
                </h1>
            </div>
        </div>
        <!-- End of Section title -->
        <!-- Product items -->
        <div class="row product-items" id="products-items">
            <!-- Single item -->
            <div class="col-10 col-sm-8 col-lg-4 mx-auto my-3">
                <div class="card single-item">
                    <div class="img-container">
                        <img src="assets/images/m1.png" alt="" class="card-img-top product-img">
                    </div>
                    <div class="card-body">
                        <div class="card-text d-flex justify-content-between text-capitalize">
                            <h5 id="item-name">Item 1</h5>
                            <span><i class="fas fa-dollar-sign"></i>350</span>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End of Single item -->
            <!-- Single item -->
            <div class="col-10 col-sm-8 col-lg-4 mx-auto my-3">
                <div class="card single-item">
                    <div class="img-container">
                        <img src="assets/images/m3.png" alt="" class="card-img-top product-img">
                    </div>
                    <div class="card-body">
                        <div class="card-text d-flex justify-content-between text-capitalize">
                            <h5 id="item-name">Item 2</h5>
                            <span><i class="fas fa-dollar-sign"></i>350</span>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End of Single item -->
            <!-- Single item -->
            <div class="col-10 col-sm-8 col-lg-4 mx-auto my-3">
                <div class="card single-item">
                    <div class="img-container">
                        <img src="assets/images/m4.png" alt="" class="card-img-top product-img">
                    </div>
                    <div class="card-body">
                        <div class="card-text d-flex justify-content-between text-capitalize">
                            <h5 id="item-name">Item 3</h5>
                            <span><i class="fas fa-dollar-sign"></i>250</span>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End of Single item -->
            <!-- Single item -->
            <div class="col-10 col-sm-8 col-lg-4 mx-auto my-3">
                <div class="card single-item">
                    <div class="img-container">
                        <img src="assets/images/m4.png" alt="" class="card-img-top product-img">
                    </div>
                    <div class="card-body">
                        <div class="card-text d-flex justify-content-between text-capitalize">
                            <h5 id="item-name">Item 4</h5>
                            <span><i class="fas fa-dollar-sign"></i>650</span>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End of Single item -->
            <!-- Single item -->
            <div class="col-10 col-sm-8 col-lg-4 mx-auto my-3">
                <div class="card single-item">
                    <div class="img-container">
                        <img src="assets/images/m3.png" alt="" class="card-img-top product-img">
                    </div>
                    <div class="card-body">
                        <div class="card-text d-flex justify-content-between text-capitalize">
                            <h5 id="item-name">Item 5</h5>
                            <span><i class="fas fa-dollar-sign"></i>150</span>
                        </div>
                    </div>
                </div>
            </div>
            <!-- Single item -->
            <div class="col-10 col-sm-8 col-lg-4 mx-auto my-3">
                <div class="card single-item">
                    <div class="img-container">
                        <img src="assets/images/m1.png" alt="" class="card-img-top product-img">
                    </div>
                    <div class="card-body">
                        <div class="card-text d-flex justify-content-between text-capitalize">
                            <h5 id="item-name">Item 6</h5>
                            <span><i class="fas fa-dollar-sign"></i>250</span>
                        </div>
                    </div>
                </div>
            </div>
            <!-- End of Single item -->
            <!-- End of Single item -->
        </div>
        <!-- End of Product items -->
    </div>
</section>
<!-- End of Featured products -->

<!-- About -->
<section id="about-sec">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-5 text-center">
                <img src="assets/images/logo.svg" alt="" width="450" height="150" class="img-fluid company-img">
            </div>
            <div class="col-lg-7 text-lg-right text-center text-color about-text">
                <h1>About company</h1>
                <p class="text">Lorem, ipsum dolor sit amet consectetur adipisicing elit. Vitae aspernatur, quam
                    quod modi quis necessitatibus adipisci quaerat quas delectus asperiores accusantium maiores sunt
                    totam officiis cumque consectetur. Neque, sit libero.</p>
            </div>
        </div>
    </div>
</section>
<!-- End of About -->