<!-- Slider -->
<section id="slide">
    <div id="carousel" class="carousel slide" data-ride="carousel">
        <ul class="carousel-indicators">
            <li data-target="#carousel" data-slide-to="0" class="active"></li>
            <li data-target="#carousel" data-slide-to="1"></li>
            <li data-target="#carousel" data-slide-to="2"></li>
        </ul>
        <div class="carousel-inner">
            <div class="carousel-item active">
                <img src="assets/images/cover1.png" class="d-block w-100" alt="Slide 1">

                <div class="carousel-caption d-none d-sm-block text-right mb-5">
                    <h1 class="display-3 title-color">Fire Station</h1>
                    <p class="lead">A fire station is a structure or other area for storing firefighting apparatus such as fire engines and related vehicles, personal protective equipment, fire hoses and other specialized equipment. Fire stations frequently contain working and living space for the firefighters and support staff.</p>
                </div>
            </div>

            <div class="carousel-item">
                <img src="assets/images/cover2.png" class="d-block w-100" alt="Slide 2">

                <div class="carousel-caption d-none d-sm-block text-right mb-5">
                    <h1 class="display-3 title-color">Iron Man</h1>
                    <p class="lead">Anthony Edward Stark is the son of wealthy industrialist and head of Stark Industries, Howard Stark, and Maria Stark. A boy genius, he enters MIT at the age of 15 to study engineering and later receives master's degrees in engineering and physics. After his parents are killed in a car accident, he inherits his father's company.</p>
                </div>
            </div>

            <div class="carousel-item">
                <img src="assets/images/cover4.png" class="d-block w-100" alt="Slide 3">

                <div class="carousel-caption d-none d-sm-block text-right mb-5">
                    <h1 class="display-3 title-color">Fat Boy</h1>
                    <p class="lead">The hero of road-commanding cruisers has arrived. Meet the Fat Boy® 30th Anniversary Limited Edition, a celebration of one of the most iconic motorcycles ever created by Harley-Davidson. Serialized badging commemorates the bike as 1 of only 2,500 in the world. Carve out a legend of your own.</p>
                </div>
            </div>

            <a href="#carousel" data-slide="prev" class="carousel-control-prev">
                <span class="carousel-control-prev-icon"></span>
            </a>
            <a href="#carousel" data-slide="next" class="carousel-control-next">
                <span class="carousel-control-next-icon"></span>
            </a>
        </div>
    </div>
</section>
<!-- End of Slider -->

<!-- Featured products -->
<section id="products" class="products py-5">
    <div class="container">
        <!-- Section title -->
        <div class="row">
            <div class="col-10 mx-auto col-sm-6 text-center">
                <h1 class="text-capitalize product-title">
                    Trending
                </h1>
            </div>
        </div>
        <!-- End of Section title -->
        <!-- Product items -->
        <div class="row row-cols-3">
            <?php
            $products = Session::get('featured');
            foreach ($products as $product) {
                // <!-- Single item -->
                echo '<div class="col-10 col-sm-8 col-lg-4 mx-auto my-3">';
                echo '<div class="card single-item">';
                echo '<div class="img-container">';
                echo '<img src="assets/models/' . $product['productSku'] . '/thumbnail.png" alt="" class="card-img-top product-img">';
                echo '</div>';
                echo '<div class="card-body">';
                echo '<div class="card-text d-flex justify-content-between text-capitalize">';
                echo '<h5 id="item-name">' . $product['productName'] . '</h5>';
                echo '<span>RM ' . $product['productPrice'] . '</span>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                echo '</div>';
                // <!-- End of Single item -->
            }
            ?>
        </div>
        <!-- End of Product items -->
    </div>
</section>
<!-- End of Featured products -->

<!-- About -->
<section id="about-sec">
    <div class="container">
        <div class="row align-items-center">
            <div class="col-lg-5 text-center">
                <img src="assets/images/logo.svg" alt="" width="450" height="150" class="img-fluid company-img">
            </div>
            <div class="col-lg-7 text-lg-right text-center text-color about-text">
                <h1>About company</h1>
                <p class="text">Founded in 2020, deLego has become one of the most popular LEGO authorized resellers in the market with 50 employees based in Penang, Malaysia.</p>
            </div>
        </div>
    </div>
</section>
<!-- End of About -->