<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="canonical" href="https://getbootstrap.com/docs/4.5/examples/navbar-static/">

    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/4.5/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/4.5/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="manifest" href="/docs/4.5/assets/img/favicons/manifest.json">
    <link rel="mask-icon" href="/docs/4.5/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
    <link rel="icon" href="../../../../assets/images/logo.png" type="image/x-icon">
    <meta name="msapplication-config" content="/docs/4.5/assets/img/favicons/browserconfig.xml">
    <meta name="theme-color" content="#563d7c">

    <!-- Font Awesome and Google Font API -->
    <script src="https://kit.fontawesome.com/0d2e3408a1.js" crossorigin="anonymous"></script>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap" rel="stylesheet">

    <!-- JQuery -->
    <link class="jsbin" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1/themes/base/jquery-ui.css" rel="stylesheet" type="text/css" />
    <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
    <script class="jsbin" src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.0/jquery-ui.min.js"></script>

    <!-- HighChart -->
    <script src="https://code.highcharts.com/highcharts.js"></script>
    <script src="https://code.highcharts.com/modules/series-label.js"></script>
    <script src="https://code.highcharts.com/modules/exporting.js"></script>
    <script src="https://code.highcharts.com/modules/export-data.js"></script>
    <script src="https://code.highcharts.com/modules/accessibility.js"></script>

    <script src="https://aframe.io/releases/1.0.0/aframe.min.js"></script>
    <!-- we import arjs version without NFT but with marker + location based support -->
    <script src="https://raw.githack.com/AR-js-org/AR.js/master/aframe/build/aframe-ar.js"></script>

    <title><?php echo $this->title ?></title>

    <!-- Custom script -->
    <link rel="stylesheet" href="../../my.css">
</head>

<body>
    <!-- Navbar -->
    <!-- <nav class="navbar navbar-expand-sm navbar-light sticky-top justify-content-between"> -->
    <nav class="navbar navbar-expand-sm navbar-dark bg-dark sticky-top justify-content-between">
        <div class="container">
            <a href="../../index" class="navbar-brand">
                <img src="../../assets/images/logo.svg" width="30" height="30" class="d-inline-block align-top" alt="Logo">
                deLego
            </a>
            <button class="navbar-toggler" data-toggle="collapse" data-target="#navbarCollapse">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarCollapse">
                <ul class="navbar-nav mx-auto">
                    <li class="nav-item <?php echo $_SERVER['REQUEST_URI'] == '/index' ? 'active' : '' ?>"><a href="../../index" class="nav-link">Home</a></li>
                    <li class="nav-item <?php echo $_SERVER['REQUEST_URI'] == '/product/building' ? 'active' : '' ?>"><a href="../../product/building" class="nav-link">Buildings</a></li>
                    <li class="nav-item <?php echo $_SERVER['REQUEST_URI'] == '/product/vehicle' ? 'active' : '' ?>"><a href="../../product/vehicle" class="nav-link">Vehicles</a></li>
                    <li class="nav-item <?php echo $_SERVER['REQUEST_URI'] == '/product/figurine' ? 'active' : '' ?>"><a href="../../product/figurine" class="nav-link">Figurines</a></li>
                </ul>
                <ul class="navbar-nav ml-auto">
                    <?php if (Session::get('userRole') == 'admin') : ?>
                        <li class="nav-item"><a href="../../admin" class="nav-link"><i class="fas fa-edit"></i></a>
                        <?php else : ?>
                        <li class="nav-item"><a href="../../user/cart" class="nav-link"><i class="fas fa-shopping-cart"></i></a>
                        <li class="nav-item"><a href="../../user" class="nav-link"><i class="fas fa-user"></i></a>
                        <?php endif; ?>

                        <?php if (Session::get('loggedIn') == true) : ?>
                        <li class="nav-item"><a href="../../user/logout" class="nav-link">Log out</a></li>
                    <?php else : ?>
                        <li class="nav-item"><a href="../../login" class="nav-link">Log in</a></li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </nav>
    <!-- End of Navbar -->