<?php
if (isset($_REQUEST['error'])) {
    echo '<div class="alert alert-danger" role="alert">';
    if ($_REQUEST['error'] == 'invaliduser') {
        echo 'Incorrect email or password';
    }
    echo '</div>';
} else if (isset($_REQUEST['signup'])) {
    if ($_REQUEST['signup'] == 'success') {
        echo '<div class="alert alert-success" role="alert">';
        echo 'Sign up successfully';
        echo '</div>';
    }
}
?>

<div class="login-form text-center">
    <form class="form-signin" action="login/run" method="post">
        <h1 class="h3 mb-3 font-weight-normal"> LOGIN</h1>
        <input type="email" name="email" class="form-control" placeholder="Email address" required autofocus>
        <input type="password" name="password" class="form-control" placeholder="Password" required>
        <div class="checkbox mb-3">
            <label>
                <input type="checkbox" value="remember-me"> Remember me
            </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit" name="login-btn">Sign in</button>
        <div class="reg-container">
            <p>New member? <a href="register">Register</a></p>
        </div>
    </form>
</div>