<div class="container">
    <br>
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <!-- <th scope="col"></th> -->
                <th scope="col">Item</th>
                <th scope="col">Name</th>
                <th scope="col">Price</th>
                <th scope="col">Quantity</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <!-- <td>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" value="option1" id="item1">
                    </div>
                </td> -->
                <td><img width=100 height=100 src="../../assets/models/FIGU0000004/thumbnail.png"> </td>
                <td>Iron Man</td>
                <td>RM 200.00</td>
                <td>1</td>
            </tr>
            <tr>
                <!-- <td>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" value="option1" id="item2">
                    </div>
                </td> -->
                <td><img width=100 height=100 src="../../assets/models/FIGU0000001/thumbnail.png"> </td>
                <td>Bat Man</td>
                <td>RM 120.00</td>
                <td>1</td>
            </tr>
            <tr>
                <!--
                <td>
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="checkbox" value="option1" id="item2">
                    </div>
                </td> -->
                <td><img width=100 height=100 src="../../assets/models/VEHI0000005/thumbnail.png"> </td>
                <td>Fat Boy</td>
                <td>RM 100.00</td>
                <td>1</td>
            </tr>
        </tbody>
    </table>
    <div class="d-flex">
        <div class="p-2">
            <h3>Total</h3>
        </div>
        <div class="ml-auto p-2">
            <h3>RM 420.00</h3>
        </div>
    </div>
    <a href="../user/checkout" class="btn btn-primary float-right" role="button" aria-disabled="true">Checkout</a>
</div>

<script>
    $('#item1').click(function() {
        $item1check = !$item1check;
        console.log($item1check);
    });
</script>