<?php if (isset($_REQUEST['error'])) {
    echo '<div class="alert alert-danger" role="alert">';
    if ($_REQUEST['error'] == 'emptyfields') {
        echo 'All fields must not be empty';
    } else if ($_REQUEST['error'] == 'invalidemailandname') {
        echo 'Invalid email address and name';
    } else if ($_REQUEST['error'] == 'invalidemail') {
        echo 'Invalid email address';
    } else if ($_REQUEST['error'] == 'invalidname') {
        echo 'Invalid name';
    } else if ($_REQUEST['error'] == 'invalidpassword') {
        echo 'Invalid password. Password must be 8 or more characters';
    } else if ($_REQUEST['error'] == 'incorrectpassword') {
        echo 'Passwords do not match';
    } else if ($_REQUEST['error'] == 'emailtaken') {
        echo 'This email has been registered';
    }
    echo '</div>';
} ?>

<div class="login-form text-center">
    <form class="form-signin" action="register/run" method="post">
        <h1 class="h3 mb-3 font-weight-normal">REGISTER</h1>
        <input type="email" class="form-control" placeholder="Email address" name="email" value="<?php echo isset($_REQUEST['email']) ? $_REQUEST['email'] : '' ?>" required autofocus>
        <input type="text" class="form-control" placeholder="Full name" name="full-name" value="<?php echo isset($_REQUEST['fullName']) ? $_REQUEST['fullName'] : '' ?>" required autofocus>
        <input type="password" class="form-control" placeholder="Password" name="password" required>
        <input type="password" class="form-control" placeholder="Confirm Password" name="confirm-password" required>
        <button class="btn btn-lg btn-primary btn-block" type="submit" name="reg-btn">Sign up</button>
        <div class="break"></div>
        <div class="reg-container">
            <p>Already have account? <a href="login">Login</a></p>
        </div>
    </form>
</div>