<br>
<div class="container">
    <?php
    if (isset($_REQUEST['status'])) {
        if ($_REQUEST['status'] == 'addsuccess') {
            echo '<div class="alert alert-success" role="alert">';
            echo 'New product added successfully';
            echo '</div>';
        } else if ($_REQUEST['status'] == 'editsuccess') {
            echo '<div class="alert alert-success" role="alert">';
            echo 'Successfully edited';
            echo '</div>';
        }
    }
    ?>

    <a href="admin/view">Manage products</a>
    <br>
    <a href="admin/add">Add products</a>
    <br>
    <a href="admin/order">Manage orders</a>
</div>