<br>
<div class="container">
    <?php
    if (isset($_REQUEST['status'])) {
        if ($_REQUEST['status'] == 'addsuccess') {
            echo '<div class="alert alert-success" role="alert">';
            echo 'New product added successfully';
            echo '</div>';
        } else if ($_REQUEST['status'] == 'editsuccess') {
            echo '<div class="alert alert-success" role="alert">';
            echo 'Successfully edited';
            echo '</div>';
        }
    }
    ?>

    <div class="row">
        <div class="col-10 col-sm-8 col-lg-3 mx-auto my-3">
            <div class="card">
                <div id="img-container">
                    <img src="assets/images/edit_product.svg" alt="" class="card-img-top" height="200px">
                </div>
                <div class="card-body">
                    <div class="card-text text-center">
                        <h6 class="function-name"><a href="admin/view">Manage products</a></h6>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-10 col-sm-8 col-lg-3 mx-auto my-3">
            <div class="card">
                <div id="img-container">
                    <img src="assets/images/add_product.svg" alt="" class="card-img-top" height="200px">
                </div>
                <div class="card-body">
                    <div class="card-text text-center">
                        <h6 class="function-name"><a href="admin/add">Add products</a></h6>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-10 col-sm-8 col-lg-3 mx-auto my-3">
            <div class="card">
                <div id="img-container">
                    <img src="assets/images/manage_order.svg" alt="" class="card-img-top" height="200px">
                </div>
                <div class="card-body">
                    <div class="card-text text-center">
                        <h6 class="function-name"><a href="admin/order">Manage orders</a></h6>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>